from __future__ import annotations

from typing import Any, Optional, Protocol

import pandas as pd

from signal_models import Signal


class DataFetcherProtocol(Protocol):
    def clear_cache(self) -> None: ...
    def fetch_all(self) -> dict[str, pd.DataFrame]: ...
    def fetch_single(self, ticker: str, period: str = ..., interval: str = ..., force: bool = ...) -> Optional[pd.DataFrame]: ...
    def fetch_multi_timeframe_all(
        self,
        trend_period: str = ...,
        trend_interval: str = ...,
        trigger_period: str = ...,
        trigger_interval: str = ...,
    ) -> dict[str, dict[str, pd.DataFrame]]: ...


class StrategyEngineProtocol(Protocol):
    def scan_all(self, data: dict[str, pd.DataFrame] | dict[str, dict[str, pd.DataFrame]]) -> list[Signal]: ...
    def get_actionable_signals(self, signals: list[Signal]) -> list[Signal]: ...
    def analyze(
        self,
        ticker: str,
        df: pd.DataFrame | dict[str, pd.DataFrame],
        enforce_sector_limit: bool = ...,
    ) -> Optional[Signal]: ...


class NotifierProtocol(Protocol):
    def send_message(self, text: str, parse_mode: str = ...) -> bool: ...
    def send_signal(self, signal: Signal) -> bool: ...
    def send_scan_summary(self, signals: list[Signal], total_scanned: int) -> bool: ...
    def send_signal_change(self, ticker: str, old_signal: Signal, new_signal: Signal) -> bool: ...
    def send_startup_message(self) -> bool: ...


class SignalRepositoryProtocol(Protocol):
    def save_signal(self, signal: Signal) -> None: ...
    def save_scan_log(self, total: int, generated: int, buys: int, sells: int) -> None: ...
    def get_latest_signal(self, ticker: str) -> Optional[dict[str, Any]]: ...
    def get_recent_signals(self, limit: int = ..., ticker: Optional[str] = ...) -> list[dict[str, Any]]: ...
    def get_performance_stats(self) -> dict[str, Any]: ...
    def add_paper_trade(
        self,
        ticker: str,
        signal_type: str,
        signal_price: float,
        signal_time: Optional[str] = ...,
        score: int = ...,
        regime: str = ...,
    ) -> None: ...
    def get_open_paper_trades(self) -> list[Any]: ...
    def update_all_paper_close(self, prices: dict[str, float]) -> None: ...
    def ping(self) -> bool: ...
