[mypy]
python_version = 3.11
warn_return_any = False
warn_unused_configs = False
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
disallow_untyped_decorators = False
no_implicit_optional = True
warn_redundant_casts = False
warn_unused_ignores = False
warn_no_return = True
warn_unreachable = False
strict_equality = True
ignore_missing_imports = True
mypy_path = src

disable_error_code = no-untyped-def,redundant-cast,unused-ignore,attr-defined,no-any-return,untyped-decorator,import-untyped,unreachable,arg-type,var-annotated
