from enum import Enum


class PositionState(str, Enum):
    ENTRY_ORDERED = "ENTRY_ORDERED"
    ENTRY_SENT = "ENTRY_SENT"
    ENTRY_PARTIAL = "ENTRY_PARTIAL"
    POSITION_OPEN = "POSITION_OPEN"
    POSITION_SETTLED = "POSITION_SETTLED"
    EXIT_ORDERED = "EXIT_ORDERED"
    EXIT_SENT = "EXIT_SENT"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"


class ExitReason(str, Enum):
    STOP_HIT = "STOP_HIT"
    TARGET_HIT = "TARGET_HIT"
    TRAILING_STOP = "TRAILING_STOP"
    MANUAL = "MANUAL"
    EMERGENCY = "EMERGENCY"
    SIGNAL_REVERSAL = "SIGNAL_REVERSAL"
    MAX_HOLDING_DAYS = "MAX_HOLDING_DAYS"


class AgentOperationalState(str, Enum):
    IDLE = "IDLE"
    SCANNING = "SCANNING"
    MONITORING = "MONITORING"
    MARKET_CLOSED = "MARKET_CLOSED"
    HALTED = "HALTED"
    PAUSED = "PAUSED"
